### ISSUE TITLE
Rename aind-ophys-fov-summary to something useful

### ISSUE THREAD

**Issue by arielleleon** [AllenNeuralDynamics/aind-ophys-fov-summary-qc#3]

**Comment by arielleleon** [comment]
This will actually be an aggregator for all pipeline qc metrics

**Comment by seanmcculloch** [comment]
aind-ophys-quality-control-aggregator

**Comment by seanmcculloch** [comment]
Created a new repo for this: https://github.com/AllenNeuralDynamics/aind-ophys-quality-control-aggregator
